### ISSUE TITLE
端口爆破似乎配置有问题？

### ISSUE THREAD

**Issue by WhatHowie** [M0nster3/OneLong#5]
端口爆破失败:
[+] resolving router 25.255.255.254 with ARP (may take some time)...
[-] FAIL: ARP timed-out resolving MAC address for router \Device\NPF_{61CF324C-1FC3-4DBE-A790-DEA354997D57}: "0.0.0.0"
    [hint] try "--router ip 192.0.2.1" to specify different router
    [hint] try "--router-mac 66-55-44-33-22-11" instead to bypass ARP
    [hint] try "--interface eth0" to change interface

未做任何调整，报错如上

**Comment by M0nster3** [comment]
https://github.com/robertdavidgraham/masscan/issues/684
这个应该还是MassDns的问题，检索网关的 MAC 地址时出现问题，可以尝试修改一下代码配置，MassDnsCmd然后去加一下，我后面去改一下传上去

**Comment by M0nster3** [comment]
https://github.com/robertdavidgraham/masscan/issues/684
这个应该是Masscan的问题，检索网关的 MAC 地址时出现问题，我后面去改一下传上去
