### ISSUE TITLE
探测网站后台模块失败

### ISSUE THREAD

**Issue by WhatHowie** [M0nster3/OneLong#6]
[INFO] 扫描网站后台，当前共有存活子域134个
[INFO] 当前扫描第1个  https://xxx.xxx.cn
[Error] Alienvault API 链接访问失败尝试切换代理
[Error] Alienvault API 读取 ExcludeLogin 文件失败
[INFO] 当前扫描第2个  https://xxx.xxx.xxx.cn
[Error] Alienvault API 读取 ExcludeLogin 文件失败

Q1：有用-proxy加代理，之前需要代理才能访问的API都成功了，不知道为什么这里会报错：链接访问失败尝试切换代理。

Q2：Alienvault API 读取 ExcludeLogin 文件失败，不太明白什么意思，config.yaml里没有找到可以添加Alienvault API的地方，ExcludeLogin文件更是没有头绪。

**Comment by M0nster3** [comment]
再dict文件夹下新建一个ExcludeLogin.txt文件
然后把这个内容添加进去，之前打包不知道为什么没有加进去
svg,css,eot,ttf,woff,jpg,png,jpeg,js,woff2,htm,gif,html,xml,swf,pdf,doc,xls,docx,xlsx.pptx,eml
